// Mock data based on OHMS database structure
import {
  Employee,
  Appointment,
  MedicalReport,
  DashboardStats,
  ReportStatusData,
  ValidationError,
  MonthlyStats,
  WorkplaceHealth,
} from '@/types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'John',
    surname: 'Smith',
    date_created: new Date('2024-01-15'),
    date_updated: new Date('2024-01-15'),
    employee_id_number: 'EMP001',
    cell_phone: '0821234567',
    email: 'john.smith@company.co.za',
    user_created: 'admin',
    user_updated: 'admin',
    section_header: 'Active Employees',
  },
  {
    id: '2',
    name: 'Sarah',
    surname: 'Johnson',
    date_created: new Date('2024-02-10'),
    date_updated: new Date('2024-02-10'),
    employee_id_number: 'EMP002',
    cell_phone: '0827654321',
    email: 'sarah.johnson@company.co.za',
    user_created: 'admin',
    user_updated: 'admin',
    section_header: 'Active Employees',
  },
  {
    id: '3',
    name: 'Michael',
    surname: 'Brown',
    date_created: new Date('2024-01-20'),
    date_updated: new Date('2024-01-20'),
    employee_id_number: 'EMP003',
    cell_phone: '0829876543',
    email: 'michael.brown@company.co.za',
    user_created: 'admin',
    user_updated: 'admin',
    section_header: 'Active Employees',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    date_created: new Date('2024-08-18'),
    date_updated: new Date('2024-08-18'),
    employee_id: '1',
    report_id: '1',
    type: 'Pre-employment Medical',
    start_datetime: new Date('2024-08-18T09:00:00'),
    end_datetime: new Date('2024-08-18T10:00:00'),
    start_date: new Date('2024-08-18'),
    end_date: new Date('2024-08-18'),
    start_time: '09:00:00',
    end_time: '10:00:00',
    notes: 'Initial screening',
    user_created: 'admin',
    user_updated: 'admin',
  },
  {
    id: '2',
    date_created: new Date('2024-08-18'),
    date_updated: new Date('2024-08-18'),
    employee_id: '2',
    type: 'Annual Medical',
    start_datetime: new Date('2024-08-18T10:30:00'),
    end_datetime: new Date('2024-08-18T11:30:00'),
    start_date: new Date('2024-08-18'),
    end_date: new Date('2024-08-18'),
    start_time: '10:30:00',
    end_time: '11:30:00',
    notes: 'Routine annual check',
    user_created: 'admin',
    user_updated: 'admin',
  },
  {
    id: '3',
    date_created: new Date('2024-08-18'),
    date_updated: new Date('2024-08-18'),
    employee_id: '3',
    report_id: '2',
    type: 'Occupational Health',
    start_datetime: new Date('2024-08-18T14:00:00'),
    end_datetime: new Date('2024-08-18T15:00:00'),
    start_date: new Date('2024-08-18'),
    end_date: new Date('2024-08-18'),
    start_time: '14:00:00',
    end_time: '15:00:00',
    user_created: 'admin',
    user_updated: 'admin',
  },
];

export const mockMedicalReports: MedicalReport[] = [
  {
    id: '1',
    date_created: new Date('2024-08-17'),
    date_updated: new Date('2024-08-18'),
    employee_id: '1',
    type: 'Pre-employment Medical',
    doctor: 'Dr. Smith',
    doctor_signoff: 'Approved',
    nurse: 'Sister Mary',
    nurse_signature: 'M.Johnson',
    report_work_status: 'Fit for work',
    notes_text: 'Employee is in good health',
    recommendation_text: 'Continue normal duties',
    user_created: 'admin',
    user_updated: 'admin',
  },
  {
    id: '2',
    date_created: new Date('2024-08-16'),
    date_updated: new Date('2024-08-17'),
    employee_id: '3',
    type: 'Occupational Health',
    doctor: 'Dr. Johnson',
    nurse: 'Sister Kate',
    nurse_signature: 'K.Williams',
    report_work_status: 'Fit with restrictions',
    notes_text: 'Minor hearing loss detected',
    recommendation_text: 'Use hearing protection',
    user_created: 'admin',
    user_updated: 'admin',
  },
  {
    id: '3',
    date_created: new Date('2024-08-15'),
    date_updated: new Date('2024-08-15'),
    employee_id: '2',
    type: 'Annual Medical',
    doctor: 'Dr. Wilson',
    nurse: 'Sister Anna',
    nurse_signature: 'A.Davis',
    report_work_status: 'Fit for work',
    notes_text: 'All vitals normal',
    user_created: 'admin',
    user_updated: 'admin',
  },
];

export const mockDashboardStats: DashboardStats = {
  todayAppointments: 8,
  completedReports: 156,
  pendingSignatures: 12,
  activeDoctors: 4,
};

export const mockReportStatus: ReportStatusData[] = [
  {
    report_type: 'Pre-employment Medical',
    total_reports: 45,
    signed_reports: 42,
    pending_signature: 3,
    completion_percentage: 93.33,
  },
  {
    report_type: 'Annual Medical',
    total_reports: 78,
    signed_reports: 71,
    pending_signature: 7,
    completion_percentage: 91.03,
  },
  {
    report_type: 'Occupational Health',
    total_reports: 33,
    signed_reports: 31,
    pending_signature: 2,
    completion_percentage: 93.94,
  },
  {
    report_type: 'Mental Health Assessment',
    total_reports: 12,
    signed_reports: 10,
    pending_signature: 2,
    completion_percentage: 83.33,
  },
];

export const mockValidationErrors: ValidationError[] = [
  {
    report_id: '4',
    employee_name: 'Lisa Anderson',
    type: 'Annual Medical',
    errors: ['Missing Doctor Signoff', 'Missing Work Status'],
  },
  {
    report_id: '5',
    employee_name: 'James Wilson',
    type: 'Pre-employment Medical',
    errors: ['Missing Nurse Signature'],
  },
  {
    report_id: '6',
    employee_name: 'Emma Thompson',
    type: 'Occupational Health',
    errors: ['Missing Doctor', 'Missing Work Status'],
  },
];

export const mockMonthlyStats: MonthlyStats[] = [
  {
    month: '2024-08',
    reports_created: 168,
    unique_employees: 142,
    doctors_involved: 4,
    avg_completion_days: 2.1,
  },
  {
    month: '2024-07',
    reports_created: 152,
    unique_employees: 134,
    doctors_involved: 3,
    avg_completion_days: 2.3,
  },
  {
    month: '2024-06',
    reports_created: 143,
    unique_employees: 128,
    doctors_involved: 4,
    avg_completion_days: 1.9,
  },
  {
    month: '2024-05',
    reports_created: 159,
    unique_employees: 145,
    doctors_involved: 4,
    avg_completion_days: 2.0,
  },
];

export const mockWorkplaceHealth: WorkplaceHealth[] = [
  {
    organisation_id: 'ORG001',
    department: 'Manufacturing',
    total_employees: 85,
    medical_reports: 78,
    fit_for_work: 72,
    not_fit: 6,
  },
  {
    organisation_id: 'ORG001',
    department: 'Administration',
    total_employees: 32,
    medical_reports: 30,
    fit_for_work: 29,
    not_fit: 1,
  },
  {
    organisation_id: 'ORG002',
    department: 'Mining Operations',
    total_employees: 124,
    medical_reports: 118,
    fit_for_work: 95,
    not_fit: 23,
  },
  {
    organisation_id: 'ORG002',
    department: 'Safety & Compliance',
    total_employees: 18,
    medical_reports: 18,
    fit_for_work: 18,
    not_fit: 0,
  },
];
